
clean:
	make -C challenge-00 clean
	make -C challenge-01 clean
#	make -C challenge-03 clean
	make -C challenge-04 clean
	make -C challenge-05 clean
	make -C challenge-06 clean
	make -C challenge-07 clean
	make -C challenge-08 clean
	make -C challenge-09 clean
	make -C challenge-11 clean
	make -C challenge-12 clean
	make -C challenge-13 clean
#	make -C challenge-14 clean
	make -C challenge-15 clean
	make -C challenge-16 clean
#	make -C challenge-17 clean
	make -C challenge-18 clean
	make -C challenge-19 clean
	make -C challenge-21 clean
	make -C challenge-22 clean
	make -C challenge-23 clean
	make -C challenge-24 clean
	make -C challenge-25 clean
	make -C challenge-26 clean
	make -C challenge-27 clean
	make -C challenge-28 clean
	make -C challenge-29 clean
