# TODO: sudo apt install linux-modules-extra-$(uname -r)
#- name: Install challenge 17 dependencies
#  become: true
#  ansible.builtin.apt:
#    cache_valid_time: 3600
#    state: present
#    name:
#      - linux-modules-extra

- name: Create potluckctf directory
  become: true
  ansible.builtin.file:
    path: /etc/potluckctf
    state: directory
    mode: '755'
    owner: root
    group: root
  
- name: Upload Challenge 17 compose config
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /etc/potluckctf/docker-compose.yml
    mode: '644'
    owner: root
    group: root

- name: Setup root docker client config
  become: true
  ansible.builtin.file:
    path: /root/.docker
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Install Challenge 17 Service
  become: true
  ansible.builtin.copy:
    src: challenge17.service
    dest: /etc/systemd/system/challenge17.service
    mode: '644'
    owner: root
    group: root
  notify:
    - daemon-reload
    - restart challenge17

- name: Setup GCP Artifact Registry auth
  become: true
  ansible.builtin.copy:
    src: config.json
    dest: /root/.docker/config.json
    mode: '600'
    owner: root
    group: root

- name: Pull the challenge heater image
  become: true
  community.docker.docker_image:
    name: "europe-west3-docker.pkg.dev/potluck-ctf/{{ challenge }}-repository/{{ challenge }}-heater:latest"
    source: pull
    force_source: "{{ upgrade_challenges | default(false) | bool }}"
  notify: restart challenge17
  register: pull_heater

- name: Tag heater image
  become: true
  community.docker.docker_image:
    name: "europe-west3-docker.pkg.dev/potluck-ctf/{{ challenge }}-repository/{{ challenge }}-heater:latest"
    repository: "heater:latest"
    pull: no
    state: present
  when: pull_heater.changed

- name: Pull the challenge interface image
  become: true
  community.docker.docker_image:
    name: "europe-west3-docker.pkg.dev/potluck-ctf/{{ challenge }}-repository/{{ challenge }}-interface:latest"
    source: pull
    force_source: "{{ upgrade_challenges | default(false) | bool }}"
  notify: restart challenge17

- name: Tag interface image
  become: true
  community.docker.docker_image:
    name: "europe-west3-docker.pkg.dev/potluck-ctf/{{ challenge }}-repository/{{ challenge }}-interface:latest"
    repository: "interface:latest"
    pull: no
    state: present
  when: pull_interface.changed

- name: Pull the challenge controller image
  become: true
  community.docker.docker_image:
    name: "europe-west3-docker.pkg.dev/potluck-ctf/{{ challenge }}-repository/{{ challenge }}-controller:latest"
    source: pull
    force_source: "{{ upgrade_challenges | default(false) | bool }}"
  notify: restart challenge17

- name: Tag controller image
  become: true
  community.docker.docker_image:
    name: "europe-west3-docker.pkg.dev/potluck-ctf/{{ challenge }}-repository/{{ challenge }}-controller:latest"
    repository: "controller:latest"
    pull: no
    state: present
  when: pull_controller.changed
  