[workspace]

members = ["crates/*"]
resolver = "2"

[profile.release]
strip = true
# lto = "fat"

[profile.dev.package."*"]
opt-level = 3

# [patch.crates-io]
# ttf2mesh-sys = { path = "ttf2mesh-sys" }
