all:
  hosts:
  children:
    scoreboard:
      hosts:
        scoreboard-a:
    challenges:
      hosts:
        challenge00-a:
        challenge00-b:

    docker:
      hosts:
        challenge00-a:
          challenge: challenge00
          docker_privileged: true
          docker_port: 31337
        challenge00-b:
          challenge: challenge00
          docker_privileged: true
          docker_port: 31337

    monitor:
      hosts:
        monitor-a:
