all:
  vars:
    ansible_user: root
    ansible_ssh_extra_args: '-R 5001:localhost:5001'
  hosts:
  children:
    scoreboard:
      hosts:
        scoreboard-a:
    challenges:
      hosts:
        challenge01-a:
        challenge01-b:
        challenge02-a:
        challenge02-b:

    monitor:
      hosts:
        monitor-a:
