all:
  hosts:
  children:
    scoreboard:
      hosts:
        scoreboard-a:
    challenges:
      children:
        challenge00:
          hosts:
            challenge00-a:
        challenge01:
          hosts:
            challenge01-a:
        challenge03:
          hosts:
            challenge03-a:
        challenge05:
          hosts:
            challenge05-a:
        challenge06:
          hosts:
            challenge06-a:
        challenge07:
          hosts:
            challenge07-a:
        challenge09:
          hosts:
            challenge09-a:
        challenge11:
          hosts:
            challenge11-a:
        challenge12:
          hosts:
            challenge12-a:
        challenge13:
          hosts:
            challenge13-a:
        challenge15:
          hosts:
            challenge15-a:
        challenge18:
          hosts:
            challenge18-a:
        challenge19:
          hosts:
            challenge19-a:
        challenge21:
          hosts:
            challenge20-a:
        challenge22:
          hosts:
            challenge22-a:
        challenge24:
          hosts:
            challenge24-a:
        challenge25:
          hosts:
            challenge25-a:
        challenge26:
          hosts:
            challenge26-a:
        challenge27:
          hosts:
            challenge27-a:
        challenge28:
          hosts:
            challenge28-a:
        challenge29:
          hosts:
            challenge29-a:

    docker:
      hosts:
        challenge00-a:
        challenge01-a:
        challenge03-a:
        challenge05-a:
        challenge06-a:
        challenge07-a:
        challenge09-a:
        challenge11-a:
        challenge12-a:
        challenge13-a:
        challenge15-a:
        challenge18-a:
        challenge19-a:
        challenge20-a:
        challenge22-a:
        challenge24-a:
        challenge26-a:
        challenge27-a:
        challenge28-a:
        challenge29-a:

    docker_single:
      hosts:
        challenge00-a:
        challenge01-a:
        challenge03-a:
        challenge05-a:
        challenge06-a:
        challenge07-a:
        challenge09-a:
        challenge12-a:
        challenge13-a:
        challenge15-a:
        challenge18-a:
        challenge19-a:
        challenge20-a:
        challenge22-a:
        challenge24-a:
        challenge26-a:
        challenge27-a:
        challenge28-a:
        challenge29-a:

    monitor:
      hosts:
        monitor-a:
