all:
  hosts:
  children:
    scoreboard:
      hosts:
        scoreboard-a:
    challenges:
      children:

    docker:
      hosts:

    docker_single:
      hosts:

    monitor:
      hosts:
        monitor-a:
