all:
  hosts:
  children:
    scoreboard:
      hosts:
        scoreboard-a:
    challenges:
      hosts:
        challenge01-a:
        challenge01-b:
        challenge02-a:
        challenge02-b:

    monitor:
      hosts:
        monitor-a:
