{
 "title": "Potluck CTF",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[5m]) * 8",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[5m]) * 8",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(node_memory_Active_bytes/node_memory_MemTotal_bytes)*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}