- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart graylog
  become: true
  ansible.builtin.service:
    name: graylog-server
    state: restarted
