- name: Install unarchive dependencies
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    state: present
    name:
      - unzip

- name: Create prometheus group
  become: true
  ansible.builtin.group:
    name: prometheus
    state: present

- name: Create prometheus user
  become: true
  ansible.builtin.user:
    name: prometheus
    group: prometheus
    comment: Prometheus
    create_home: no
    shell: /usr/sbin/nologin
    state: present
    system: true

- name: Create prometheus config directory
  become: true
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Prometheus config
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart prometheus

- name: Create prometheus directory
  become: true
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Download and unpack prometheus library files
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.48.0/prometheus-2.48.0.linux-amd64.tar.gz
    include:
      - prometheus-2.48.0.linux-amd64/consoles
      - prometheus-2.48.0.linux-amd64/console_libraries
    dest: /etc/prometheus
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Download and unpack prometheus binaries
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.48.0/prometheus-2.48.0.linux-amd64.tar.gz
    include:
      - prometheus-2.48.0.linux-amd64/prometheus
      - prometheus-2.48.0.linux-amd64/promtool
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Prometheus systemd service
  become: true
  ansible.builtin.copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '644'
  notify:
    - daemon-reload
    - restart prometheus

- name: enable Prometheus service
  become: true
  ansible.builtin.service:
    name: prometheus
    enabled: true
