- name: Setup variables
  hosts: all
  tasks:
    - name: Setup private ips
      ansible.builtin.set_fact:
        potluckctf_monitor_host: "{{ groups['monitor'][0] }}"

- name: Setup Challenge 25
  hosts: challenge25
  roles:
    - role: challenge-25

- name: Setup Challenge 11
  hosts: challenge11
  roles:
    - role: challenge-11

- name: Setup Challenge 01
  hosts: challenge01
  roles:
    - role: challenge-01

- name: Setup single container challenges
  hosts: docker_single
  roles:
    - role: challenge-docker
