- name: Setup variables
  hosts: all
  tasks:
    - name: Setup private ips
      ansible.builtin.set_fact:
        potluckctf_monitor_host: "{{ groups['monitor'][0] }}"

- name: Setup Challenge 25
  hosts: challenge25
  roles:
    - role: challenge-25

#- name: Setup Docker servers
#  hosts: docker_single
#  roles:
#    #- role: docker
#    - role: challenge-docker