- name: Setup variables
  hosts: all
  tasks:
    - name: Setup private ips
      ansible.builtin.set_fact:
        potluckctf_monitor_host: "{{ groups['monitor'][0] }}"

- name: Setup Docker servers
  hosts: challenge11
  roles:
    #- role: docker
    - role: challenge-11
