- name: Setup variables
  hosts: all
  tasks:
    - name: Setup private ips
      ansible.builtin.set_fact:
        potluckctf_monitor_host: "{{ groups['monitor'][0] }}"

- name: Basic setup
  hosts: all
  roles:
    - role: serversetup
    - role: node_exporter
    - role: rsyslog
      vars:
        syslog_server: "{{ potluckctf_monitor_host }}"

- name: Setup monitor server
  hosts: monitor
  roles:
    - role: graylog
    - role: prometheus
