- name: Setup variables
  hosts: all
  tasks:
    - name: Setup private ips
      ansible.builtin.set_fact:
        potluckctf_monitor_host: "{{ groups['monitor'][0] }}"

- name: Basic setup
  hosts: all
  roles:
    - role: serversetup
    - role: node_exporter
    - role: rsyslog
      vars:
        syslog_server: "{{ potluckctf_monitor_host }}"

- name: Setup monitor server
  hosts: monitor
  roles:
    - role: graylog
    - role: prometheus
    - role: grafana

- name: Setup Docker servers
  hosts: docker
  roles:
    - role: docker
    - role: nginx

- name: Setup Challenge 25
  hosts: challenge25
  roles:
    - role: challenge-25

- name: Setup Challenge 11
  hosts: challenge11
  roles:
    - role: challenge-11

- name: Setup Challenge 01
  hosts: challenge01
  roles:
    - role: challenge-01

- name: Setup single container challenges
  hosts: docker
  roles:
    - role: challenge-docker

- name: Setup scoreboard servers
  hosts: scoreboard
  roles:
    - role: scoreboard
    - role: docker
