version: '3'

services:
  nginx:
    build:
      context: .
      args:
        FLAG: "potluck{placeholder}"
    ports:
      - 4242:80
    
    
    # Locally you can uncomment these lines.
    
    # volumes:
    #   - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf
    #   - ${PWD}/xsl:/etc/nginx/xsl
    #   - ${PWD}/njs:/etc/nginx/njs
    #   - ${PWD}/www:/var/www


    # And you can run this command to auto reload nginx on file change.
    # while inotifywait -q -e close_write  njs/* conf/* xsl/* www/*; do docker compose exec nginx nginx -s reload; done

    # Bon appetit!